### ISSUE TITLE
during hide fragment getShowingFragment of FragmentsUtils return com.bumptech.glide.manager.SupportRequestManagerFragment insted of com.zach.znavigator.ZNavigation.FragmentWrapper

### ISSUE THREAD

**Issue by tnavadiya** [ZachBublil/ZNavigator#1]

**Comment by Zachinio** [comment]
Can you post some of your code to make it easier to help you?
getShowingFragment would return the first visible fragment in the fragment manager you supplied it,
that means if you added another fragment above the FragmentWrapper you will get that fragment instead.

The FragmentWrapper designed for seeping the fragment lifecycle of show and hide , and for loading the child with the childFragmentManager for creating a new back stack of fragments under the same tab,
