### ISSUE TITLE
The library does not return the parent fragment back to the main fragment.

### ISSUE THREAD

**Issue by iamkurtgoz** [ZachBublil/ZNavigator#2]
The library does not return the parent fragment back to the main fragment.

**Comment by iamkurtgoz** [comment]
@ZachBublil

**Comment by Zachinio** [comment]
I don't understand what do you mean.
Can you explain what you are trying to do, or tell me how to reconstrcut the issue?

**Comment by iamkurtgoz** [comment]
I call the child fragment again in the child fragment and the application fails.
@ZachBublil

**Comment by Zachinio** [comment]
Use the below code to open another child fragment:
`                ZNavigation.openChildFragment(getFragmentManager(),new ChildFragment());
`

**Comment by iamkurtgoz** [comment]
I am calling another fragment with the same code in the fragment I opened using this code, and I get an error.

**Comment by Zachinio** [comment]
Post the error please and steps to reproduce please

**Comment by iamkurtgoz** [comment]
Okay. Wait
