### ISSUE TITLE
The opened child fragments do not close

### ISSUE THREAD

**Issue by iamkurtgoz** [ZachBublil/ZNavigator#3]
I went to the Fragment mistake, but now I have a slightly different mistake

[This is a error video](https://streamable.com/ziaao)

**Comment by Zachinio** [comment]
This is not a bug in ZNavigator library, you should check if you already initiated the BottomNavigationBar.

**Comment by iamkurtgoz** [comment]
I've added exactly what you've done. You can not make your library beautiful by closing all my questions.
