### ISSUE TITLE
Bottom navigation menu items change but fragment is not replacing 

### ISSUE THREAD

**Issue by hrgdeveloper** [ZachBublil/ZNavigator#4]
hello thanks for your great libs . 

https://imgur.com/a/1UShXDq
this is provided  gif to  show problem 
some times the bottom navigation view items changes but fragment will stuck in the current  and  wont change 
all my fragments extends ZNavigationFragment and evry thing is like the sample 

also i have noticed that this happen even  for the sample you have  provided some  times ; my mean is that some times  fragments changes wihout problem but sometimes it stuck .

**Comment by hrgdeveloper** [comment]
i found whats the problem ; the problem was with glide;
when you use glide library and instantiate glide with fragment context  it will add a glide fragment to fragment stack  . so you have to use application context for instantiating glide in fragment instead of getActivity();

**Comment by Zachinio** [comment]
Can I close the issue then?
